version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  manylinux2014-aarch64:
    parameters:
      cibw_build:
        type: string
        default: "cp37-*"

    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
             uname -m 
             docker run -e ARANGO_RANDOM_ROOT_PASSWORD=1 -d --name arangodb-instance arangodb/arangodb
             arangodb/arangodb:3.7.7 --server.jwt-secret-keyfile=/tmp/keyfile
             docker cp tests/static/service.zip arango:/tmp/service.zip
             docker cp tests/static/keyfile arango:/tmp/keyfile
             docker start arango
             git fetch --prune --unshallow
             python -m pip install --upgrade pip setuptools wheel
             pip install .[dev]
             black --check .
             flake8 .
             isort --check --profile=black .
             mypy arango
             py.test --complete --cov=arango --cov-report=xml
workflows:
  version: 2.1
  main:
    jobs:
      - manylinux2014-aarch64:
          matrix:
            parameters:
              cibw_build:
                - "cp37*"
